# ===========================
# UI Automation
# ===========================
base.url=https://lms-b2b.do.dibimbing.id/dibimbingqa/login

email=arwendymelyn@dibimbing.id
password=s2et9bh6l

# ===========================
# GraphQL API
# ===========================
graphql.url=https://lmsb2b.do.dibimbing.id/graphql

graphql.username=b2bserveruser
graphql.password=ENAcA3Sog22681sAKvih8KkpDKvF2aQ6

company.id=811637b1-9989-4d45-a9f5-220c5f2354f7
company.slug=dibimbingqa
