name: QA Automation Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  regression-testing:
    name: Regression Testing

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Regression Test
        env:
          CI: true
        run: mvn clean test

      - name: Upload Surefire Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
          if-no-files-found: ignore